/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#e1e2ec',
        'on-secondary-container': '#00515d',
        'surface-container': '#1d2027',
        'tertiary': '#ffb786',
        'on-tertiary': '#502400',
        'on-primary-container': '#00285d',
        'tertiary-fixed-dim': '#ffb786',
        'surface-container-low': '#191b23',
        'on-tertiary-container': '#461f00',
        'tertiary-container': '#df7412',
        'secondary-container': '#00cbe6',
        'on-primary-fixed': '#001a42',
        'outline': '#8c909f',
        'tertiary-fixed': '#ffdcc6',
        'on-primary': '#002e6a',
        'on-tertiary-fixed-variant': '#723600',
        'error': '#ffb4ab',
        'secondary-fixed': '#a2eeff',
        'on-surface-variant': '#c2c6d6',
        'surface-container-lowest': '#0b0e15',
        'primary-container': '#4d8eff',
        'surface-dim': '#10131a',
        'surface': '#10131a',
        'on-primary-fixed-variant': '#004395',
        'surface-tint': '#adc6ff',
        'surface-bright': '#363941',
        'surface-container-high': '#272a31',
        'surface-container-highest': '#32353c',
        'outline-variant': '#424754',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'inverse-surface': '#e1e2ec',
        'on-error': '#690005',
        'inverse-on-surface': '#2e3038',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed-dim': '#2fd9f4',
        'on-secondary-fixed': '#001f25',
        'on-tertiary-fixed': '#311400',
        'on-secondary-fixed-variant': '#004e5a',
        'on-surface': '#e1e2ec',
        'on-secondary': '#00363e',
        'background': '#10131a',
        'primary': '#adc6ff',
        'primary-fixed': '#d8e2ff',
        'inverse-primary': '#005ac2',
        'surface-variant': '#32353c',
        'secondary': '#5de6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'container-max': '1440px',
        'stack-lg': '32px',
        'margin-desktop': '64px',
        'section-gap': '120px',
      },
      fontFamily: {
        metric: ['Geist', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        metric: ['28px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      animation: {
        'pulse-dot': 'pulse-dot 2s infinite ease-in-out',
        'pipeline-flow': 'pipeline-flow 2s infinite linear',
      },
      keyframes: {
        'pulse-dot': {
          '0%': { transform: 'scale(0.9)', opacity: '0.7' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'scale(0.9)', opacity: '0.7' },
        },
        'pipeline-flow': {
          '0%': { backgroundPosition: '0% 50%' },
          '100%': { backgroundPosition: '100% 50%' },
        },
      },
      boxShadow: {
        'glow-blue': '0 0 20px rgba(59, 130, 246, 0.2)',
        'glow-primary': '0 0 30px rgba(173, 198, 255, 0.15)',
      },
    },
  },
  plugins: [],
}
